# Generated by Django 3.2.10 on 2022-03-13 00:01

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Cliente')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('ethnicity', models.CharField(choices=[('Português', 'português'), ('Brasileiro', 'brasileiro'), ('Africano', 'africano')], max_length=10, verbose_name='Etnia')),
                ('status', models.CharField(choices=[('Ativo', 'ativo'), ('Inativo', 'inativo')], default='Ativo', max_length=10, verbose_name='Status')),
                ('street', models.CharField(max_length=50, verbose_name='Logradouro')),
                ('number', models.IntegerField(verbose_name='Nº')),
                ('complement', models.CharField(blank=True, max_length=10, verbose_name='Complemento')),
                ('city', models.CharField(choices=[('\tLisboa\t', '\tLisboa\t'), ('\tSintra\t', '\tSintra\t'), ('\tVilaNovadeGaia\t', '\tVilaNovadeGaia\t'), ('\tCorvo\t', '\tCorvo\t')], max_length=26, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('Ag', 'Algarve'), ('Al', 'Alto Alentejo'), ('Ba', 'Baixo Alentejo'), ('Be', 'Beira Alta'), ('Bx', 'Beira Baixa'), ('Bl', 'Beira Litoral'), ('Dl', 'Douro Litoral'), ('Ex', 'Estremadura'), ('Mb', 'Minho Braga'), ('Ri', 'Ribatejo'), ('Tm', 'Trás os Montes'), ('Ma', 'Madeira*'), ('Ac', 'Açores*')], max_length=26, verbose_name='Província')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw', models.BooleanField(default=False, verbose_name='Retirar')),
                ('data', models.DateField(verbose_name='Data de entrega')),
                ('formpayment', models.CharField(choices=[('Pix', 'pix'), ('Cartão', 'cartão'), ('Dinheiro', 'dinheiro')], max_length=11, verbose_name='Forma pgto')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=11, null=True, verbose_name='Total')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Pronto', 'Pronto'), ('Aguardando', 'Aguardando'), ('Enviado', 'Enviado'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=10, verbose_name='Condição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pedido', to='clientorders.client')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Produto')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('image', models.ImageField(blank=True, upload_to='produtos/%Y', verbose_name='Imagem do produto')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialmedia', models.CharField(max_length=50, verbose_name='Rede Social')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_midiasocial', to='clientorders.client')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celphone', models.CharField(max_length=14, verbose_name='Celular')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_telefone', to='clientorders.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True, verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal')),
                ('details', models.CharField(blank=True, max_length=300, verbose_name='Detalhes')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientorders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='produto_pedido', to='clientorders.product')),
            ],
        ),
    ]
