# Generated by Django 3.2.10 on 2022-03-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientorders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data',
            new_name='date',
        ),
    ]
