# Generated by Django 3.2.10 on 2022-03-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formset', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
