# Generated by Django 3.2.10 on 2022-03-10 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formset', '0002_rename_products_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
